# =============================================================================
# Generated Packer HCL for Platform9 Private Cloud
# =============================================================================
# This file was generated by generate_packer.py
# Configuration: rocky97
# =============================================================================

# Packer required plugins
packer {
  required_plugins {
    openstack = {
      version = ">= 1.1.3"
      source  = "github.com/hashicorp/openstack"
    }
  }
}

# =============================================================================
# Variables
# =============================================================================

# OpenStack Connection Variables (can be overridden via CLI or environment)
variable "os_auth_url" {
  type    = string
  description = "OpenStack authentication URL"
  default = "https://platform9.example.com:5000/v3"
}

variable "os_username" {
  type    = string
  description = "OpenStack username"
  default = "admin"
}

variable "os_password" {
  type    = string
  description = "OpenStack password"
  default = ""
  sensitive = true
}

variable "os_project_name" {
  type    = string
  description = "OpenStack project name"
  default = "admin"
}

variable "os_project_domain_name" {
  type    = string
  description = "OpenStack project domain name"
  default = "default"
}

variable "os_user_domain_name" {
  type    = string
  description = "OpenStack user domain name"
  default = "default"
}

variable "os_region" {
  type    = string
  description = "OpenStack region"
  default = "RegionOne"
}

variable "os_tenant_id" {
  type    = string
  description = "OpenStack tenant ID"
  default = ""
}

variable "os_tenant_name" {
  type    = string
  description = "OpenStack tenant name"
  default = ""
}

# Configuration Variables (from vars.json)
variable "instance_name" {
  type    = string
  description = "Name for the VM instance"
  default = "rocky97-vm"
}

variable "golden_image_name" {
  type    = string
  description = "Golden image name to use"
  default = "Rocky-9-GenericCloud-latest"
}

variable "golden_image_uuid" {
  type    = string
  description = "Golden image UUID to use"
  default = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
}

variable "flavor" {
  type    = string
  description = "Flavor for the VM"
  default = "m1.small"
}

variable "network_uuid" {
  type    = string
  description = "Network UUID for the VM"
  default = "net-uuid-12345"
}

variable "network_name" {
  type    = string
  description = "Network name for the VM"
  default = "private-network"
}

variable "domain_name" {
  type    = string
  description = "Domain name"
  default = "default"
}

variable "volume_name" {
  type    = string
  description = "Name for the data volume"
  default = "rocky97-data-volume"
}

variable "volume_size_gb" {
  type    = number
  description = "Size of the volume in GB"
  default = 20
}

variable "availability_zone" {
  type    = string
  description = "Availability zone for resources"
  default = "az1"
}

variable "key_pair" {
  type    = string
  description = "SSH keypair name"
  default = "rocky-key"
}

variable "ssh_username" {
  type    = string
  description = "SSH username"
  default = "rocky"
}

variable "ssh_public_key" {
  type    = string
  description = "Path to SSH public key file"
  default = "files/rocky_key.pub"
}

# Security groups as comma-separated string
variable "security_groups" {
  type    = string
  description = "Security groups (comma-separated)"
  default = "default"
}

# =============================================================================
# Locals
# =============================================================================

locals {
  # Parse security groups from comma-separated string
  security_groups_list = split(",", var.security_groups)
  
  # Cloud-init user data file path
  user_data_file = "${ path.root }/files/user-data"
}

# =============================================================================
# Packer Sources (Builders)
# =============================================================================

# ---------------------------------------------------------------------
# Volume Builder - Creates a volume from golden image
# ---------------------------------------------------------------------
source "openstack" "data-volume" {
  # Connection
  auth_url          = var.os_auth_url
  username          = var.os_username
  password          = var.os_password
  project_name      = var.os_project_name
  domain_name       = var.domain_name
  project_domain_name = var.os_project_domain_name
  user_domain_name  = var.os_user_domain_name
  region            = var.os_region
  tenant_id         = var.os_tenant_id
  tenant_name       = var.os_tenant_name
  
  # Image Configuration - Use golden image by UUID
  image_uuid        = var.golden_image_uuid
  image_name        = var.golden_image_name
  
  # Volume Configuration
  use_blockstorage_volume = true
  volume_size             = var.volume_size_gb
  volume_name             = var.volume_name
  volume_type             = var.volume_type
  delete_on_termination   = true
  
  # Availability Zone
  availability_zone = var.availability_zone
  
  # This is a null builder - it just creates the volume from image
  # No actual instance is built, we just prepare the volume
  instance_name     = "temp-volume-builder"
  flavor            = var.flavor
  
  # Communicator (required but not used for volume-only)
  communicator      = "none"
}

# ---------------------------------------------------------------------
# VM Server Builder - Creates a VM from golden image
# Note: OpenStack connection uses environment variables:
#   OS_AUTH_URL, OS_USERNAME, OS_PASSWORD, OS_PROJECT_NAME, OS_DOMAIN_NAME, OS_REGION
# ---------------------------------------------------------------------
source "openstack" "vm-server" {
  # Instance Configuration
  instance_name        = var.instance_name
  source_image        = var.golden_image_uuid
  image_name          = var.golden_image_name
  flavor               = var.flavor

  # Network Configuration
  networks             = [var.network_uuid]

  # Security Groups
  security_groups      = local.security_groups_list

  # SSH Configuration
  ssh_keypair_name    = var.key_pair
  ssh_username        = var.ssh_username

  # Cloud-init user data
  user_data_file      = local.user_data_file

  # Volume Configuration
  volume_size         = var.volume_size_gb

  # Availability Zone
  availability_zone   = var.availability_zone

  # Communicator
  communicator        = "ssh"
  ssh_port            = 22
  ssh_timeout         = "5m"

  # Run configuration
  pause_before_connecting = "30s"
}

# =============================================================================
# Build Configuration
# =============================================================================

build {
  name = "rocky97"
  
  # ---------------------------------------------------------------------
  # Build 1: Create data volume from golden image
  # ---------------------------------------------------------------------
  sources = [
    "source.openstack.vm-server"
  ]
  
  # ---------------------------------------------------------------------
  # Provisioner: Configure the VM after creation
  # ---------------------------------------------------------------------
  
  # Shell provisioner to configure the VM
  provisioner "shell" {
    execute_command = "sudo { .Path }"
    inline = [
      # Update system
      "yum update -y",
      
      # Install required packages
      "yum install -y git ansible curl wget",
      
      # Create data directory
      "mkdir -p /mnt/data",
      
      # Display volume info
      "lsblk",
      
      # If volume is attached as /dev/vdb, format and mount it
      "if [ -b /dev/vdb ]; then",
      "  parted -s /dev/vdb mklabel msdos || true",
      "  parted -s /dev/vdb mkpart primary ext4 0% 100% || true",
      "  mkfs.ext4 /dev/vdb1",
      "  mkdir -p /mnt/data",
      "  mount /dev/vdb1 /mnt/data",
      "  echo '/dev/vdb1 /mnt/data ext4 defaults 0 0' >> /etc/fstab",
      "fi",
      
      # If volume is attached as /dev/sdb, format and mount it
      "if [ -b /dev/sdb ]; then",
      "  parted -s /dev/sdb mklabel msdos || true",
      "  parted -s /dev/sdb mkpart primary ext4 0% 100% || true",
      "  mkfs.ext4 /dev/sdb1",
      "  mkdir -p /mnt/data",
      "  mount /dev/sdb1 /mnt/data",
      "  echo '/dev/sdb1 /mnt/data ext4 defaults 0 0' >> /etc/fstab",
      "fi",
      
      # Clean up
      "yum clean all",
      
      # Display mount info
      "df -h",
      
      # Create test file
      "echo 'VM provisioned successfully!' > /mnt/data/provisioned.txt"
    ]
  }
  
  # ---------------------------------------------------------------------
  # Post-provisioning: Output information
  # ---------------------------------------------------------------------
  provisioner "shell-local" {
    command = "echo '========================================' && echo 'Packer build completed successfully!' && echo '========================================' && echo 'Instance Name: rocky97-vm' && echo 'Volume Name: rocky97-data-volume' && echo '========================================'"
  }
}

# =============================================================================
# Volume Creation and Attachment (External Script)
# =============================================================================
# The volume will be created and attached during the build process.
# To create the volume separately before VM creation, use the following:
#
# 1. Create volume from image:
#    openstack volume create --image <image-uuid> --size <size> <volume-name>
#
# 2. Create VM:
#    openstack server create --image <image-uuid> --flavor <flavor> \
#        --network <network-uuid> --key-name <keypair> <instance-name>
#
# 3. Attach volume to VM:
#    openstack server add volume <instance-name> <volume-name>
#
# =============================================================================
